add new validate module

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -51,14 +51,25 @@ jobs:
               fi
             fi
           done
-            
+      - name: Process check
+        if: always()
+        run: exit $CHECK_STATUS
+  validate-module:
+    runs-on: ubuntu-latest
+    name: Validate Terraform module
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
       - name: terraform validate
         uses: dflook/terraform-validate@v2
         id: validate
         with:
-          path: infrastructure
-      - name: Process check
-        if: always()
-        run: exit $CHECK_STATUS
+          path: my-terraform-config
+
+      - name: Validate failed
+        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
+        run: echo "terraform validate failed"
+
 
  
